# prettier-ignore

version: 2.1

orbs:
  node: circleci/node@4.7.0

references:
  docker_node_base: &docker_node_base  
    image: circleci/node:16.10.0

jobs:
  checkout_code:
    docker:
      - <<: *docker_node_base
    steps:
      - checkout

  install_node_dependencies:
    docker:
      - <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
  
  lint_css:
    docker:
      - <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint CSS
          command: npm run lint:css 

  lint_javascript:
    docker:
      - <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint Javascript
          command: npm run lint 

  test_jest:
    docker:
      - <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Jest
          command: npm run test:coverage

workflows:
  version: 2
  lint_and_test:
    jobs:
      - checkout_code
      - install_node_dependencies:
          requires:
            - checkout_code
      - lint_css:
          requires:
            - install_node_dependencies
      - lint_javascript:
          requires:
            - install_node_dependencies
      - test_jest:
          requires:
            - install_node_dependencies
            - lint_javascript
            - lint_css
