# prettier-ignore

version: 2.1

orbs:
  node: circleci/node@4.7.0

references:
  docker_node_base: &docker_node_base  
    image: circleci/node:16.10.0

jobs:
  checkout_code:
    <<: *docker_node_base
    steps:
      - checkout

  install_dependencies:
    <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages

  lint_javascript:
    <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint:js

  lint_css:
    <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint:css

  test_javascript:
    <<: *docker_node_base
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Run tests with Jest"
          command:
            npm test -- --runInBand --no-cache --coverage

workflows:
  version: 2

  joelw_dev:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint_javascript:
          requires:
            - install_dependencies
      - lint_css:
          requires:
            - install_dependencies
      - test_javascript:
          requires:
            - install_dependencies
            - lint_javascript
            - lint_css
